### ISSUE TITLE
Redirecting Standard Input

### ISSUE THREAD

**Issue by matthewsheeran** [slavagu/ConsoleAppLauncher#3]
The code does has RedirectStandardInput = true but I am actually looking to implement it by redirecting stdin from a string parameter of lines if it is indeed possible as I want to avoid having to write say a Python script out to a file before executing it.  (I had attempted this on my own unsucessfully before turning to your code.) Let me make it clear as one can do:
ConsoleApp("...python.exe", "-c import \"platform;print(platform.architecture()[0]);exit(0)\"")
ConsoleApp("...python.exe", "<bits.py")
After writing out a "bits.py" containing:
platform
print(platform.architecture()[0])
exit(0)

But I want to actually invoke a ConsoleApp like library with ("...python.exe", ref string stdin, string.. args) 
ConsoleApp("...python.exe", ref stdin, null) say where string stdin in this case = 
@"platform
print(platform.architecture()[0])
exit(0)
"

Is it even possible or must I write out the python scripts e.g. "bits.py" to  temp file and do a ConsoleApp("...python.exe", "<bits.py") all the time.

Am I being too abitious or niave to think that this could and should even be possible.  BTW I am mostly interested in CPython (MinGW) from C# (for geospatial scripting using OSGeo4W pyQGIS and GDAL-OGR)  that concerns me and interests me in this..

Let me know if you can offer any advice? Regards.

**Comment by matthewsheeran** [comment]
I noticed that the stdin Write and WriteLine are missing form the package that are in the original StackOverflow example code which I can try.  I was also using "cmd.exe /c \"\"...\python.exe\" -c ... 2>&1\"" to merge stderr with stdout.  I also discovered from another posting that my Writes may not have been getting to the Python process so I will try it again without the cmd.exe as I no lomnger need it uisng either of your codes modified again although I am curious why you dropped the stdin Writes.

**Comment by matthewsheeran** [comment]
Nope I have had no joy either with MinGW or GnuWin32 "cat.exe" WriteLine or Write and I pretty  that the ConsoleAppManager is doing the right thing thread-wise but it just doesnt get through or may depend upon the nature of the getch() type calls in python.exe cat.exe notepad.exe etc.
I even tried notepad.exe..

**Comment by slavagu** [comment]
Supplying input redirect parameters doesn't work with Process.Start for some reason so the only option I can think of is exposing Write/WriteLine on StandardInput. You will then be able to call app.WiteLine(...) to provide input to your console application. I can add Write/WriteLine to ConsoleApp if that will help.

**Comment by matthewsheeran** [comment]
I tried it with my own code and the ConsoleAppManager similar to yours from here and attached: https://stackoverflow.com/questions/21848271/redirecting-standard-input-of-console-application 

[ConsoleAppManager.cs.txt](https://github.com/slavagu/ConsoleAppLauncher/files/1020888/ConsoleAppManager.cs.txt)

Still no joy with C python.exe cat.exe's notepad.exe etc.

if you put it in I will try it again and tell you if it works but for now I am keeping my same API with a "#filename" as first input row which I then write as a Temp filename and execute the command with the file on disk as the last parameter something much like a bash SheBang if it exists and the code is trvial.  Works like a charm and hides this file action code under the API so I can change the former code later without touching the API if I ever get stdin redirection truly working but I do have the feeling that it may indeed be more trouble than it is worth.

The only hint to the problem and solution I have found is here: https://stackoverflow.com/questions/9506606/console-input-redirect

So if I really want to pursue as an answered stated it may be case of looking into C++ code here for this: https://sourceforge.net/projects/console/

Which I am not going to pursue just at the moment as I have my interim solution and I can random overwrite with chars to the same Temp file length before deleting if I wish to secure my scripts.

But do let me know if you put Write/WriteLine in and I will test again.  This seems like a must have if one truly wants to encapsulate Async Console App functionality such as in your solution.  It is frustating and annoying to have to resort to a hack without fixing it however elegant my "#filename" (which is quite general for any app with file parameter and not only Python BTW) hack might be for now and I can help you to improve ConsoleApp and expand its user base as there is _nothing_ out there that does input redirection sucessfully other than full replacement shells internally like that above to look into.  :-)

Kindest Regards.

**Comment by matthewsheeran** [comment]
You could use a generated random Temp filename instead of the "#filename.py" first line and hide the effective pseudo-redirected stdin to disk file entirely (as far as the API is concerned it would appear as a string stdin) but I prefer to use the namimg for easier debugging disabling its overwrite and deletion and being able to find the file created in Temp by name for now! Only an issue if an when I actually have multiple windows/threads doing the same #filename.py Python processing at the same time for now!

**Comment by matthewsheeran** [comment]
> Supplying input redirect parameters doesn't work with Process.Start for some reason so the only option I > can think of is exposing Write/WriteLine on StandardInput. You will then be able to call app.WiteLine(...) > to provide input to your console application. I can add Write/WriteLine to ConsoleApp if that will help.

Please do add so I can ditch the ConsoleAppManager code and revist your Writes from ConsoleApp you can basically copy their Write/WriteLine code into yours for now.

Thanks.

**Comment by slavagu** [comment]
I've added support for Write and WriteLine, see usage example in should_get_input_redirect() test. New package published to nuget.org, hope this helps.
