### ISSUE TITLE
What if the console app also prompts for a user's input?

### ISSUE THREAD

**Issue by sivabudh** [slavagu/ConsoleAppLauncher#4]
Suppose the command we wanted to run asks for a user password, how do we "type" the password in and also capture the console app's entire output?

**Comment by sivabudh** [comment]
Thanks, I will give it a try. I need to communicate with a console app written in C/C++ using _getch() function which reads from the console buffer (not the standard input).

It's one tough cookie.

**Comment by slavagu** [comment]
Hope the solution worked :)
