### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by quicoli** [slavagu/ConsoleAppLauncher#5]
Hello, thank you for this library.

I'd like to use your library in a .net core application, could you release a .net standard version of it?

**Comment by slavagu** [comment]
Hi! I haven't been doing .net development for a few years now. Please check out https://github.com/Tyrrrz/CliWrap It's a neat implementation with async/await and targets .net core as well. Hope this helps.

**Comment by quicoli** [comment]
Thank you :)
